name: Python CI/CD

on:  # Триггеры запуска
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  # ОС для запуска

    steps:
    # 1. Загружаем код репозитория
    - uses: actions/checkout@v4

    # 2. Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # 3. Устанавливаем зависимости (аналог before_script)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Запускаем тесты и линтеры
    - name: Run pytest
      run: pytest tests/

    - name: Run mypy
      run: mypy myhw/

    - name: Run Black
      run: black --check --diff myhw/

    - name: Run isort
      run: isort --check-only myhw/

    - name: Run flake8
      run: flake8 myhw/