name: Python CI/CD

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    # 1. Загружаем код репозитория
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest myhw/tests/


    - name: Run Black
      run: black  myhw/

    - name: Run isort
      run: isort --check-only --diff --profile black myhw/

    - name: Run flake8
      run: flake8 myhw/
